name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/iris_project_grp8:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/iris_project_grp8:latest

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          container-registry: efreiprediction.azurecr.io
          image: iris_project_grp8:latest
          container-name: iris_project_grp8
          azure-region: France Central
          dns-name-label: iris_project_grp8
          ports: 8080
          auto-scale: true
          auto-scale-rule: "NumberOfIncomingRequests > 100"
