name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/iris-project-grp8:latest
          az acr build --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --image iris-project-grp8:latest .

      - name: Deploy to Azure Container App
        uses: azure/ACR-Deploy@v1
        with:
          acr-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          image-name: iris-project-grp8:latest
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          app-name: ContainerGroup8
          tenant-id: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
          client-id: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          client-secret: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
